[package]
name = "dungeon_crawler"
version = "0.1.0"
authors = ["Arthur Renon <renon.arthur@gmail.com>"]
edition = "2018"

[dependencies]
bracket-lib = "~0.8.1"
legion = "=0.3.1"
serde = { version = "=1.0.115" }
ron = "=0.6.1"

[profile.release]
lto = "thin"